### ISSUE TITLE
"microbs validate" coughs up a hairball when trying to validate kubectl version

### ISSUE THREAD

**Issue by atsaloli** [microbs-io/microbs#2]
What's wrong with this picture?  :)

```
ubuntu@microbs-test:~$ microbs validate

Validating dependencies...
✓ node is correct version [using=20.18.1, required>=16.14.0]
✓ npm is installed
✓ npm is correct version [using=10.9.2, required>=8.3.0]
✓ docker is installed
✓ docker is correct version [using=27.3.1, required>=20.10.0]
✓ docker is running
✓ kubectl is installed
Cannot read properties of null (reading '1')
TypeError: Cannot read properties of null (reading '1')
    at validateKubectlVersion (/usr/lib/node_modules/@microbs.io/cli/src/commands/validate.js:150:86)
    at validateDependencies (/usr/lib/node_modules/@microbs.io/cli/src/commands/validate.js:288:3)
    at Object.run (/usr/lib/node_modules/@microbs.io/cli/src/commands/validate.js:366:3)
    at module.exports.run (/usr/lib/node_modules/@microbs.io/cli/src/index.js:61:38)
    at Object.<anonymous> (/usr/lib/node_modules/@microbs.io/cli/microbs:7:9)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:173:12)
...
```

I have the latest kubectl:

```
ubuntu@microbs-test:~$ kubectl version
Client Version: v1.31.3
Kustomize Version: v5.4.2
Server Version: v1.31.0
ubuntu@microbs-test:~$
```

**Comment by atsaloli** [comment]
I see I'm not the first person to run into this... Fixed by https://github.com/microbs-io/microbs/pull/1 ?
